# Generated by Django 2.2.27 on 2026-07-23 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=64)),
                ('usage_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('usage_class', models.CharField(choices=[('aggregate', 'Aggregate'), ('consumed', 'Consumed')], default='consumed', max_length=32)),
                ('task_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenchiro_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenchiro_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usageevents',
            index=models.Index(fields=['user', 'created_at'], name='tenchiro_us_user_id_64df4c_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevents',
            index=models.Index(fields=['task_uuid'], name='tenchiro_us_task_uu_36654a_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevents',
            index=models.Index(fields=['usage_class', 'created_at'], name='tenchiro_us_usage_c_a4a034_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevents',
            index=models.Index(fields=['usage_class', 'usage_type'], name='tenchiro_us_usage_c_804bab_idx'),
        ),
    ]
