# Generated by Django 2.2.27 on 2026-07-25 12:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenchiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_appname', models.SlugField(default='tenchiro-odm', help_text="The slug name used to uniquely identify the app with the portal service. Do not use special characters or spaces other than '_' or '-' in this name. The name must be defined in the application configuration in the portal service.", max_length=64)),
                ('webhook_enabled', models.BooleanField(default=True, help_text='Toggle outbound webhook dispatching for usage events. This synchronizes usage betweeen the app and portal service and updates the usage pools.')),
                ('webhook_target_url', models.CharField(default='https://localhost:8000/pool/api/usage/{appname}/{username}/', help_text='Destination URL where UsageEvent batches are posted. Can incorporate {appname} or {username} if necessary. These will be substituted with the corresponding values for the request.', max_length=512)),
                ('webhook_batch_size', models.PositiveIntegerField(default=50, help_text='Maximum number of usage events to bundle per transmission request.')),
                ('webhook_max_retries', models.PositiveIntegerField(default=3, help_text='Maximum retry attempts before flagging a transmission attempt as failed.')),
                ('webhook_timeout_seconds', models.PositiveIntegerField(default=10, help_text='HTTP POST request timeout in seconds.')),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Auxiliary settings for future SaaS modules without requiring schema migrations.', null=True)),
            ],
            options={
                'verbose_name': 'Settings',
                'verbose_name_plural': 'Settings',
                'db_table': 'tenchiro_setting',
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(max_length=64)),
                ('usage_value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('usage_class', models.CharField(choices=[('aggregate', 'Aggregate'), ('consumed', 'Consumed')], default='consumed', max_length=32)),
                ('task_uuid', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenchiro_usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenchiro_usage_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsagePool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=64)),
                ('resource_class', models.CharField(choices=[('aggregate', 'Aggregate'), ('consumed', 'Consumed')], default='consumed', max_length=32)),
                ('available', models.DecimalField(decimal_places=6, max_digits=20)),
                ('portal_message_uuid', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenchiro_usage_pools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenchiro_usage_pools',
                'ordering': ['user', 'resource_name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(default='portal', help_text="Target or source service (e.g., 'portal').", max_length=64)),
                ('message_uuid', models.CharField(db_index=True, help_text='Unique identifier for this specific message transmission.', max_length=64)),
                ('direction', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], default='sent', help_text='Whether the message was sent or received by this app.', max_length=16)),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code (e.g., 200, 400, 500).', null=True)),
                ('sequence_key', models.CharField(db_index=True, help_text='Monotonic sequence string for ordering in format: 2026-07-24T20:59:00.123456Z:001', max_length=64)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Stores small payloads, cached JSON responses for retries, or diagnostic error messages.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction attempt was recorded.')),
                ('usage_events', models.ManyToManyField(blank=True, db_table='tenchiro_webhook_usage_events', help_text='Usage events associated with this specific transmission attempt.', related_name='webhook_logs', to='tenchiro.UsageEvent')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user for the transaction, if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenchiro_webhook_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenchiro_webhook_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UsageEvents',
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['service', 'sequence_key'], name='tenchiro_we_service_258aab_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['message_uuid'], name='tenchiro_we_message_d33078_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['direction', 'response_status'], name='tenchiro_we_directi_0cc42f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['created_at'], name='tenchiro_we_created_dd3527_idx'),
        ),
        migrations.AddIndex(
            model_name='usagepool',
            index=models.Index(fields=['user', 'resource_name'], name='tenchiro_us_user_id_5abad1_idx'),
        ),
        migrations.AddIndex(
            model_name='usagepool',
            index=models.Index(fields=['user', 'updated_at'], name='tenchiro_us_user_id_778bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='usagepool',
            index=models.Index(fields=['portal_message_uuid'], name='tenchiro_us_portal__3a994d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagepool',
            unique_together={('user', 'resource_name')},
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'created_at'], name='tenchiro_us_user_id_d4b051_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['task_uuid'], name='tenchiro_us_task_uu_37b594_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['usage_class', 'created_at'], name='tenchiro_us_usage_c_f7f3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['usage_class', 'usage_type'], name='tenchiro_us_usage_c_bbc670_idx'),
        ),
    ]
