# Generated by Django 2.2.27 on 2026-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenchiro', '0002_auto_20260725_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='webhook_applabel',
            field=models.CharField(default='Tenchiro ODM', help_text='The user readable label used to describe this app.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'usage_type', 'usage_class', 'created_at'], name='idx_usage_usr_typ_cls_creat'),
        ),
    ]
