# Generated by Django 2.2.27 on 2026-07-27 10:21

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenchiro', '0003_auto_20260727_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhooklog',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Stores small payloads, cached JSON responses for retries, or diagnostic error messages.', null=True),
        ),
    ]
